# travis CI config
language: python
python:
  - 2.7
  - 3.4.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  - pypy3

# Use fast travis build infrastructure explicitly
dist: trusty
sudo: false

install:
  - pip install --upgrade setuptools
  - pip install "pip>=7.1.0"
  - pip install .
  - pip install -r test_requirements.txt
script:
  - cd tests
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python -E -Wall -tt -bb run_testsuite.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -E -Wall -bb run_testsuite.py; fi
# pypy doesn't like -tt option
